version: "3"

# 默认会创建一个私有的docker网络,并支持服务发现，即绑定服务名到ip
services:
        coupon-server:
                container_name: coupon-server
                # 使用服务镜像,暴露3000端口到主机端。测试的时候直接连接本地的3000端口即可
                image: littledarren/coupon_server
                  #使用下面的命令保证容器执行但不开启www服务
                command: tail -f /dev/null 
                ports:
                        - "3000:3000"
                depends_on:
                        - coupon-db
                        - coupon-redis
                # 做一些资源上的限制，保证测试代码不影响服务器性能
                deploy:
                  resources:
                    limits:
                      cpus : '4'
                      memory : 2G
        
        coupon-db:
                container_name: coupon-db
                image: littledarren/coupon_db  
                ports:
                        - "23306:27017"
                deploy:
                  resources:
                    limits:
                      cpus : '1'
                      memory : 2G

        coupon-redis:
                container_name: coupon-redis
                image: redis:5.0.7-alpine3.10
                deploy:
                  resources:
                    limits:
                      cpus : '1'
                      memory : 2G
