FROM node:12.13.1-alpine3.10
WORKDIR /server
COPY ./server /server/
COPY ./docker-composes/sysctl.conf /etc/sysctl.conf

RUN sed -i 's/localhost/coupon-db/g' /server/src/config.js \
    && npm i \
    && npm i -g pm2 
VOLUME /server
EXPOSE 3000
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["pm2", "start", "pm2-3.json", "--no-daemon"]
