FROM node:12.13.1-alpine3.10
WORKDIR /server
COPY ./server /server/
COPY ./docker-composes/sysctl.conf /etc/sysctl.conf

RUN sed -i 's/localhost/coupon-db/g' /server/src/config.js \
    && sed -i 's/127.0.0.1/192.168.233.133/g' /server/stressTest/api.js \ 
    && npm i --registry=https://registry.npm.taobao.org
VOLUME /server
WORKDIR /server/stressTest
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["node", "index.js"]
