FROM node:12.13.1-alpine3.10
WORKDIR /server
COPY ./server /server/
COPY ./docker-composes/sysctl.conf /etc/sysctl.conf

RUN sed -i 's/localhost/coupon-db/g' /server/src/config.js \
    && sed -i 's/127.0.0.1/coupon-redis/g' /server/src/config.js \
    && npm i --registry=https://registry.npm.taobao.org \
    && npm i --registry=https://registry.npm.taobao.org -g pm2 
VOLUME /server
EXPOSE 3000
ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["./run.sh", "2"]
